// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/adatvedelem/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/adatvedelem">> = Specific
  const handler = {} as typeof import("../../app/adatvedelem/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categories">> = Specific
  const handler = {} as typeof import("../../app/admin/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/faqs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/faqs">> = Specific
  const handler = {} as typeof import("../../app/admin/faqs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/maintenance">> = Specific
  const handler = {} as typeof import("../../app/admin/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/media">> = Specific
  const handler = {} as typeof import("../../app/admin/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/messages">> = Specific
  const handler = {} as typeof import("../../app/admin/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/posts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/posts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/posts/[id]/versions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/[id]/versions">> = Specific
  const handler = {} as typeof import("../../app/admin/posts/[id]/versions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/posts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts/new">> = Specific
  const handler = {} as typeof import("../../app/admin/posts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../app/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/references/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/references">> = Specific
  const handler = {} as typeof import("../../app/admin/references/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings/users">> = Specific
  const handler = {} as typeof import("../../app/admin/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tags">> = Specific
  const handler = {} as typeof import("../../app/admin/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/web-vitals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/web-vitals">> = Specific
  const handler = {} as typeof import("../../app/admin/web-vitals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/kategoria/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/kategoria/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/kategoria/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/preview/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/preview/[token]">> = Specific
  const handler = {} as typeof import("../../app/blog/preview/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/400/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/400">> = Specific
  const handler = {} as typeof import("../../app/error/400/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/401/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/401">> = Specific
  const handler = {} as typeof import("../../app/error/401/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/403/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/403">> = Specific
  const handler = {} as typeof import("../../app/error/403/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/429/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/429">> = Specific
  const handler = {} as typeof import("../../app/error/429/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/503/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/error/503">> = Specific
  const handler = {} as typeof import("../../app/error/503/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gyik/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gyik">> = Specific
  const handler = {} as typeof import("../../app/gyik/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kapcsolat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kapcsolat">> = Specific
  const handler = {} as typeof import("../../app/kapcsolat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../app/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/megoldasaink/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/megoldasaink">> = Specific
  const handler = {} as typeof import("../../app/megoldasaink/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/referenciak/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referenciak">> = Specific
  const handler = {} as typeof import("../../app/referenciak/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rolunk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rolunk">> = Specific
  const handler = {} as typeof import("../../app/rolunk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/szervezeti-kihivasok/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/szervezeti-kihivasok">> = Specific
  const handler = {} as typeof import("../../app/szervezeti-kihivasok/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/categories">> = Specific
  const handler = {} as typeof import("../../app/api/admin/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/faqs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/faqs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/faqs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/faqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/faqs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/faqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/maintenance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/maintenance">> = Specific
  const handler = {} as typeof import("../../app/api/admin/maintenance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media">> = Specific
  const handler = {} as typeof import("../../app/api/admin/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/media/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/media/upload">> = Specific
  const handler = {} as typeof import("../../app/api/admin/media/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/messages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/messages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/messages">> = Specific
  const handler = {} as typeof import("../../app/api/admin/messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/password">> = Specific
  const handler = {} as typeof import("../../app/api/admin/password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/posts/[id]/preview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/[id]/preview">> = Specific
  const handler = {} as typeof import("../../app/api/admin/posts/[id]/preview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/posts/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/posts/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/posts/[id]/versions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/[id]/versions">> = Specific
  const handler = {} as typeof import("../../app/api/admin/posts/[id]/versions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/posts/draft/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts/draft">> = Specific
  const handler = {} as typeof import("../../app/api/admin/posts/draft/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/references/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/references/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/references/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/references/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/references">> = Specific
  const handler = {} as typeof import("../../app/api/admin/references/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tags/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tags/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tags/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tags/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tags">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tags/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/web-vitals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics/web-vitals">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/web-vitals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/related-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/related-posts">> = Specific
  const handler = {} as typeof import("../../app/api/blog/related-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cron/publish-scheduled/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cron/publish-scheduled">> = Specific
  const handler = {} as typeof import("../../app/api/cron/publish-scheduled/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/status">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/error/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/error">> = Specific
  const handler = {} as typeof import("../../app/error/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
