// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/adatvedelem" | "/admin" | "/admin/categories" | "/admin/faqs" | "/admin/login" | "/admin/maintenance" | "/admin/media" | "/admin/messages" | "/admin/posts" | "/admin/posts/[id]" | "/admin/posts/[id]/versions" | "/admin/posts/new" | "/admin/references" | "/admin/settings" | "/admin/settings/users" | "/admin/tags" | "/admin/web-vitals" | "/blog" | "/blog/[slug]" | "/blog/kategoria/[slug]" | "/blog/preview/[token]" | "/error/400" | "/error/401" | "/error/403" | "/error/429" | "/error/503" | "/gyik" | "/kapcsolat" | "/maintenance" | "/megoldasaink" | "/referenciak" | "/rolunk" | "/szervezeti-kihivasok"
type AppRouteHandlerRoutes = "/api/admin/categories" | "/api/admin/categories/[id]" | "/api/admin/faqs" | "/api/admin/faqs/[id]" | "/api/admin/maintenance" | "/api/admin/media" | "/api/admin/media/upload" | "/api/admin/messages" | "/api/admin/messages/[id]" | "/api/admin/password" | "/api/admin/posts" | "/api/admin/posts/[id]" | "/api/admin/posts/[id]/preview" | "/api/admin/posts/[id]/versions" | "/api/admin/posts/draft" | "/api/admin/references" | "/api/admin/references/[id]" | "/api/admin/tags" | "/api/admin/tags/[id]" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/analytics/web-vitals" | "/api/auth/[...nextauth]" | "/api/blog/related-posts" | "/api/contact" | "/api/cron/publish-scheduled" | "/api/maintenance/status"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/error"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/adatvedelem": {}
  "/admin": {}
  "/admin/categories": {}
  "/admin/faqs": {}
  "/admin/login": {}
  "/admin/maintenance": {}
  "/admin/media": {}
  "/admin/messages": {}
  "/admin/posts": {}
  "/admin/posts/[id]": { "id": string; }
  "/admin/posts/[id]/versions": { "id": string; }
  "/admin/posts/new": {}
  "/admin/references": {}
  "/admin/settings": {}
  "/admin/settings/users": {}
  "/admin/tags": {}
  "/admin/web-vitals": {}
  "/api/admin/categories": {}
  "/api/admin/categories/[id]": { "id": string; }
  "/api/admin/faqs": {}
  "/api/admin/faqs/[id]": { "id": string; }
  "/api/admin/maintenance": {}
  "/api/admin/media": {}
  "/api/admin/media/upload": {}
  "/api/admin/messages": {}
  "/api/admin/messages/[id]": { "id": string; }
  "/api/admin/password": {}
  "/api/admin/posts": {}
  "/api/admin/posts/[id]": { "id": string; }
  "/api/admin/posts/[id]/preview": { "id": string; }
  "/api/admin/posts/[id]/versions": { "id": string; }
  "/api/admin/posts/draft": {}
  "/api/admin/references": {}
  "/api/admin/references/[id]": { "id": string; }
  "/api/admin/tags": {}
  "/api/admin/tags/[id]": { "id": string; }
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/analytics/web-vitals": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/blog/related-posts": {}
  "/api/contact": {}
  "/api/cron/publish-scheduled": {}
  "/api/maintenance/status": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/blog/kategoria/[slug]": { "slug": string; }
  "/blog/preview/[token]": { "token": string; }
  "/error": {}
  "/error/400": {}
  "/error/401": {}
  "/error/403": {}
  "/error/429": {}
  "/error/503": {}
  "/gyik": {}
  "/kapcsolat": {}
  "/maintenance": {}
  "/megoldasaink": {}
  "/referenciak": {}
  "/rolunk": {}
  "/szervezeti-kihivasok": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/error": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
